service: serverless-graphql-client

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-finch

custom:
  client:
    bucketName: s3-bucketname-serverless-graphql
    distributionFolder: build
