service: serverless-graphql-apollo

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  serverless-offline:
    port: 4000
    babelOptions:
      presets: ["es2015", "stage-2"]
  webpackIncludeModules: true
  region: ${opt:region, self:provider.region}
  cognito_pool_id: <cognito_pool_id>
  account_id: <aws_account_id>

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
        authorizer:
          arn:aws:cognito-idp:${self:custom.region}:${self:custom.account_id}:userpool/${self:custom.cognito_pool_id}
  graphiql:
    handler: handler.graphiqlHandler
    events:
    - http:
        path: graphiql
        method: get
        cors: true
        authorizer:
          arn:aws:cognito-idp:${self:custom.region}:${self:custom.account_id}:userpool/${self:custom.cognito_pool_id}
